### PR TITLE
Added version 1.0.1

### PR DESCRIPTION
**Pull request by jabamula**
I updated J2000_JNow to a new version, which I numbered 1.0.1 and added files:
J2000_JNow_101.app MacOS app
J2000_JNow_101.py python file
README.md updated

Kai,
I wasn't sure should I myself remove the old version file:
J2000_JNow.py
J2000_JNow_rev1
readme..txt

### CODE REVIEW

**Comment by smart-underworld** [comment]
It's best to print the version string as part of your script, but leave the name of the script independent of the version number. GitHub will have revision history so anyone can get any previous versions. You can also tag a branch with a tag.

**Comment by smart-underworld** [comment]
I do see the change is significant. So I will go ahead and merge so a new folder will be created.

**Comment by jabamula** [comment]
Hello Kai,Thank you, I will follow your advice on the name and version script. The folder now has the old files. Is it ok to make the changes (remove them) in my clone branch and then I will pull a request.The terminology is still not clear and I don’t understand what branch I can tag. And what that means. // Jari smart-underworld ***@***.***> kirjoitti 28.2.2024 kello 21.15:﻿
It's best to print the version string as part of your script, but leave the name of the script independent of the version number. GitHub will have revision history so anyone can get any previous versions. You can also tag a branch with a tag.

**Comment by smart-underworld** [comment]
Yes. GitHub will have all your revision histories so even if you delete a
file from branch, the main will have historical revisions.

**Pull request merged**
